# Change these first
owner: pbarriat # Your GitHub organization or username, where this repository lives
repo: elic-status # The name of this repository

sites:
  - name: Website
    url: https://www.elic.ucl.ac.be
  - name: Gogs
    url: https://gogs.elic.ucl.ac.be
  - name: Shiny
    url: https://shiny.elic.ucl.ac.be
  - name: Ferdium
    url: https://ferdium.elic.ucl.ac.be
  - name: Nextcloud
    url: https://nextcloud.elic.ucl.ac.be

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /elic-status
  logoUrl: https://raw.githubusercontent.com/pbarriat/elic-status/9f80c3696288d6831dd422d5e2458d0233da9bce/assets/elic-icon.png
  name: ELIC status
  introTitle: "**ELIC Status** shows all service status for [ELIC](https://www.elic.ucl.ac.be)."
  introMessage: All system status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
